### DISCUSSION TITLE
help with custom css

### DISCUSSION THREAD

**Discussion by ggrrll** [jupyter/notebook#7152] [Q&A]
Hi, 

I am trying to reduce side margins
I added

```
:root {
    --jp-notebook-max-width: 100% !important;
}
```

in my _custom.css_  as suggested here 
https://stackoverflow.com/questions/21971449/how-do-i-increase-the-cell-width-of-the-jupyter-ipython-notebook-in-my-browser/76778615#76778615

I get the expected result in notebooks, but the tree looks bad 👇 

![Screen Shot 2023-11-14 at 16 36 19](https://github.com/jupyter/notebook/assets/15370425/ff84a80f-dbf0-4786-a6c9-52e2dc6af1d2)

any idea?

thanks

**Comment by jtpio** [comment]
@ggrrll maybe tweaking the selector as follows would help keep it scoped to the notebooks page only?

```css
:root body[data-notebook='notebooks'] {
  --jp-notebook-max-width: 100% !important;
}
```

**Comment by ggrrll** [comment]
thanks 

tbh, I am not sure anymore what was going wrong

now that simple solution works, by editing indeed `notebook/custom/custom.css` 

for the sake of completeness, I report hereby my env. (on linux mint 21.1)

```
IPython          : 8.16.1
ipykernel        : 6.25.2
ipywidgets       : 8.1.1
jupyter_client   : 8.4.0
jupyter_core     : 5.2.0
jupyter_server   : 2.8.0
jupyterlab       : 4.0.7
nbclient         : 0.8.0
nbconvert        : 7.9.2
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : not installed
traitlets        : 5.11.2
```

**Comment by gcbeltramini** [comment]
It's always good to have alternative solutions. This one also works for me:

```css
.jp-Notebook {
  --jp-notebook-max-width: 100% !important;
}
```

Editing the `.container` used to achieve the same behavior in the past, but it's no longer effective for me:

```css
.container {
  width: 100% !important;
}
```
