### ISSUE TITLE
CSS: "alert" is missing "margin-top"

### ISSUE THREAD

**Issue by mgeier** [jupyter/notebook#1390]
Currently, the `alert` class has only `margin-bottom` (I guess this comes from bootstrap):

```css
.alert {
    margin-bottom: 18px;
}
```

Since most other elements use only `margin-top`, those alert boxes are much too close to whatever comes before them.

Probably something like this could be added:

```css
.rendered_html * + .alert {
    margin-top: 18px;
}
```

... or it could just be added unconditionally, like the original `margin-bottom`:

```css
.alert {
    margin-top: 18px;
}
```

But probably the best solution would be, to overwrite the original `margin-bottom` and just do the same as with plain old `<p>`:

```css
.rendered_html .alert {
    margin-bottom: initial;
}
.rendered_html * + .alert {
    margin-top: 1em;
}
```
