### ISSUE TITLE
Installed package won't import in notebook

### ISSUE THREAD

**Issue by fonnesbeck** [jupyter/notebook#2359]
I'm using the notebook from a conda env, and have the environment set up with all of my required packages installed. However, when I try to import one of these (seaborn) in the notebook, I get an import error suggesting it is not installed. This works fine from the command line and I can confirm using the `conda` command within the notebook that the package is installed:

![](http://d.pr/i/rkyJ+)

Running notebook 4.4.1 from conda.

Interestingly, when I try to import `notebook` from inside of a notebook, I get the same error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-09fdb2483669> in <module>()
----> 1 import notebook
      2 
      3 notebook.__version__

ImportError: No module named 'notebook'
```

**Comment by fonnesbeck** [comment]
To followup, I have even created a fresh conda env, but I get the exact same error.

**Comment by fonnesbeck** [comment]
I can further confirm that installing Seaborn via pip does not fix this issue.

**Comment by fonnesbeck** [comment]
Complete reinstallation of Anaconda fixed the issue.

**Comment by fonnesbeck** [comment]
This occurs with pip-installed packages as well as conda:

![](http://d.pr/i/6hhK+)

**Comment by ccordoba12** [comment]
I think you need to restart the kernel for this to work. Besides, you have to be sure to be using the right `pip` (e.g. `pip` that comes with Anaconda instead of system `pip`).

**Comment by fonnesbeck** [comment]
I've restarted the kernel multiple times, without success. I can also confirm that it is the pip installed into the env. I can import this library from the ipython console without issue.

**Comment by fonnesbeck** [comment]
Just to clarify, I am using a conda env based on this yml:

```yml
name: dev

channels:
 - conda-forge
 
dependencies:
- python=3.6
- arrow
- basemap
- blaze
- bokeh
- cython
- dask
- engarde
- ipython
- jupyter
- notebook
- ipyparallel
- ipywidgets
- joblib
- jupyter_client
- jupyter_core
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- jupyterlab
- line_profiler
- mkl-service
- numexpr
- numba
- numpy
- openpyxl
- pandas
- patsy
- pillow
- pip
- pylint
- scikit-learn
- scipy
- seaborn
- snakeviz
- sympy
- tensorflow
- theano
- xlrd
- pip:
  - GPy
  - PyCap
  - pystan
  - rpy2
  - git+https://github.com/GPflow/GPflow.git#egg=GPflow
  - git+https://github.com/pymc-devs/pymc3.git#egg=pymc3
```

The env was created and all packages were installed without error, but some packages can be loaded into the notebook, while others were not.
