### ISSUE TITLE
Cell output on the side

### ISSUE THREAD

**Issue by ptbrowne** [jupyter/notebook#2897]
I find having the output cells on my code on the side of the input simpler and more space-efficient. I put in a [Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=fr) extension a custom CSS to do that.

I wondered if it was something that was already in Jupyter, or could be included ?. If not, maybe some people will have the same problem as I had and could benefit from my solution :)

Here is the CSS:

```css
#notebook-container {
    width: 100%
}

.code_cell {
   flex-direction: row !important;
}

.code_cell .input {
    width: 50%
}

.code_cell .output_wrapper {
    width: 50%
}
```

Result : 

![image](https://user-images.githubusercontent.com/465582/31146291-78e56240-a886-11e7-96e3-a3fe069025c7.png)
